package com.lauchenauer.nextbusperth.dao;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stopDaoConfig;
    private final DaoConfig routeDaoConfig;
    private final DaoConfig stopTimeDaoConfig;
    private final DaoConfig journeyDaoConfig;
    private final DaoConfig journeyRouteDaoConfig;

    private final StopDao stopDao;
    private final RouteDao routeDao;
    private final StopTimeDao stopTimeDao;
    private final JourneyDao journeyDao;
    private final JourneyRouteDao journeyRouteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stopDaoConfig = daoConfigMap.get(StopDao.class).clone();
        stopDaoConfig.initIdentityScope(type);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        stopTimeDaoConfig = daoConfigMap.get(StopTimeDao.class).clone();
        stopTimeDaoConfig.initIdentityScope(type);

        journeyDaoConfig = daoConfigMap.get(JourneyDao.class).clone();
        journeyDaoConfig.initIdentityScope(type);

        journeyRouteDaoConfig = daoConfigMap.get(JourneyRouteDao.class).clone();
        journeyRouteDaoConfig.initIdentityScope(type);

        stopDao = new StopDao(stopDaoConfig, this);
        routeDao = new RouteDao(routeDaoConfig, this);
        stopTimeDao = new StopTimeDao(stopTimeDaoConfig, this);
        journeyDao = new JourneyDao(journeyDaoConfig, this);
        journeyRouteDao = new JourneyRouteDao(journeyRouteDaoConfig, this);

        registerDao(Stop.class, stopDao);
        registerDao(Route.class, routeDao);
        registerDao(StopTime.class, stopTimeDao);
        registerDao(Journey.class, journeyDao);
        registerDao(JourneyRoute.class, journeyRouteDao);
    }
    
    public void clear() {
        stopDaoConfig.getIdentityScope().clear();
        routeDaoConfig.getIdentityScope().clear();
        stopTimeDaoConfig.getIdentityScope().clear();
        journeyDaoConfig.getIdentityScope().clear();
        journeyRouteDaoConfig.getIdentityScope().clear();
    }

    public StopDao getStopDao() {
        return stopDao;
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

    public StopTimeDao getStopTimeDao() {
        return stopTimeDao;
    }

    public JourneyDao getJourneyDao() {
        return journeyDao;
    }

    public JourneyRouteDao getJourneyRouteDao() {
        return journeyRouteDao;
    }

}
