package com.lauchenauer.nextbusperth.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.lauchenauer.nextbusperth.dao.Stop;
import com.lauchenauer.nextbusperth.dao.Route;

import com.lauchenauer.nextbusperth.dao.StopDao;
import com.lauchenauer.nextbusperth.dao.RouteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stopDaoConfig;
    private final DaoConfig routeDaoConfig;

    private final StopDao stopDao;
    private final RouteDao routeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stopDaoConfig = daoConfigMap.get(StopDao.class).clone();
        stopDaoConfig.initIdentityScope(type);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        stopDao = new StopDao(stopDaoConfig, this);
        routeDao = new RouteDao(routeDaoConfig, this);

        registerDao(Stop.class, stopDao);
        registerDao(Route.class, routeDao);
    }
    
    public void clear() {
        stopDaoConfig.getIdentityScope().clear();
        routeDaoConfig.getIdentityScope().clear();
    }

    public StopDao getStopDao() {
        return stopDao;
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

}
