package com.lauchenauer.nextbusperth.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.lauchenauer.nextbusperth.dao.StopTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STOP_TIME.
*/
public class StopTimeDao extends AbstractDao<StopTime, Long> {

    public static final String TABLENAME = "STOP_TIME";

    /**
     * Properties of entity StopTime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Route_id = new Property(1, Long.class, "route_id", false, "ROUTE_ID");
        public final static Property Departure_time = new Property(2, java.util.Date.class, "departure_time", false, "DEPARTURE_TIME");
    };

    private Query<StopTime> route_StopTimeListQuery;

    public StopTimeDao(DaoConfig config) {
        super(config);
    }
    
    public StopTimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STOP_TIME' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ROUTE_ID' INTEGER," + // 1: route_id
                "'DEPARTURE_TIME' INTEGER);"); // 2: departure_time
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_STOP_TIME_DEPARTURE_TIME_ROUTE_ID ON STOP_TIME" +
                " (DEPARTURE_TIME,ROUTE_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STOP_TIME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StopTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long route_id = entity.getRoute_id();
        if (route_id != null) {
            stmt.bindLong(2, route_id);
        }
 
        java.util.Date departure_time = entity.getDeparture_time();
        if (departure_time != null) {
            stmt.bindLong(3, departure_time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StopTime readEntity(Cursor cursor, int offset) {
        StopTime entity = new StopTime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // route_id
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)) // departure_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StopTime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRoute_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDeparture_time(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StopTime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StopTime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "stopTimeList" to-many relationship of Route. */
    public synchronized List<StopTime> _queryRoute_StopTimeList(Long route_id) {
        if (route_StopTimeListQuery == null) {
            QueryBuilder<StopTime> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.Route_id.eq(route_id));
            route_StopTimeListQuery = queryBuilder.build();
        } else {
            route_StopTimeListQuery.setParameter(0, route_id);
        }
        return route_StopTimeListQuery.list();
    }

}
