package com.lauchenauer.nextbusperth.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table STOP_TIME.
 */
public class StopTime {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public StopTime() {
    }

    public StopTime(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
